In [52]:
import pandas as pd
import numpy as np

## Q1. Pandas version

In [53]:
pd.__version__

'3.0.6'

## Q2. Records Count

In [54]:
df = pd.read_csv('car_fuel_efficiency_2026.csv')
df.head(n=2)

,model_year,origin,fuel_type,drivetrain,num_doors,engine_displacement,num_cylinders,horsepower,vehicle_weight,acceleration,fuel_efficiency_mpg
0,2006,Europe,Gasoline,Front-wheel drive,4,2180,6,243.0,3870,NaN,31.9
1,2008,Europe,Diesel,Front-wheel drive,4,2390,6,272.0,4210,NaN,31.3

In [55]:
# How many records are in the dataset?
len(df)

10000

## Q3. Fuel types

In [56]:
# How many fuel types are presented in the dataset?
df['fuel_type'].nunique()

3

## Q4. Missing values

In [57]:
# How many columns in the dataset have missing value?
df.isnull().sum()

model_year               0
origin                   0
fuel_type                0
drivetrain               0
num_doors                0
engine_displacement      0
num_cylinders            0
horsepower             877
vehicle_weight           0
acceleration           264
fuel_efficiency_mpg      0
dtype: int64

## Q5. Max fuel efficiency

In [58]:
# What is the max fuel efficiency of cars from Asia?
df[df['origin'] == 'Asia']['fuel_efficiency_mpg'].max()

np.float64(41.2)

## Q6. Median value of horsepower

In [59]:
# Find the median value of the horsepower column in the dataset.
df['horsepower'].median()

np.float64(254.0)

In [60]:
# Next, calculate the most frequent value of the same horsepower column.
df['horsepower'].mode()[0]

np.float64(252.0)

In [61]:
# Use the fillna method to fill the missing values in the horsepower column with the most frequent value from the previous step.
most_frequent_value = df['horsepower'].mode()[0]
df.fillna({'horsepower': most_frequent_value}, inplace=True)

,model_year,origin,fuel_type,drivetrain,num_doors,engine_displacement,num_cylinders,horsepower,vehicle_weight,acceleration,fuel_efficiency_mpg
0,2006,Europe,Gasoline,Front-wheel drive,4,2180,6,243.0,3870,NaN,31.9
1,2008,Europe,Diesel,Front-wheel drive,4,2390,6,272.0,4210,NaN,31.3
2,1996,Asia,Gasoline,Front-wheel drive,5,2320,6,267.0,4240,17.3,27.5
3,1989,Europe,Gasoline,Front-wheel drive,4,2130,6,258.0,4490,18.7,28.5
4,1994,USA,Diesel,Front-wheel drive,3,2580,7,304.0,4510,17.5,31.0
...,...,...,...,...,...,...,...,...,...,...,...
9995,2005,USA,Gasoline,All-wheel drive,4,2470,6,271.0,4690,18.9,27.4
9996,1993,Asia,Gasoline,All-wheel drive,2,2300,6,244.0,4370,19.0,30.0
9997,2014,USA,Gasoline,All-wheel drive,3,2480,6,267.0,4590,18.4,28.1
9998,2004,USA,Hybrid,Rear-wheel drive,5,2180,6,270.0,4450,20.9,32.2
9999,2011,USA,Diesel,Front-wheel drive,4,2380,6,295.0,4370,17.6,30.2

In [62]:
# Now, calculate the median value of horsepower once again.
df['horsepower'].median()

np.float64(252.0)

## Q7. Sum of weights

In [63]:
# Select all the cars from Asia
df_asia = df[df['origin'] == 'Asia']

# Select only columns vehicle_weight and model_year
df_asia_selected = df_asia[['vehicle_weight', 'model_year']]

# Select the first 7 value
df_asia_selected_first7 = df_asia_selected.head(7)

# Get the underlying NumPy array. Let's call it X.
X = df_asia_selected_first7.to_numpy()

# Compute matrix-matrix multiplication between the transpose of X and X. To get the transpose, use X.T. Let's call the result XTX.
XTX = X.T.dot(X)

# Invert XTX
XTX_inv = np.linalg.inv(XTX)

# Create an array y with values [1100, 1300, 800, 900, 1000, 1100, 1200].
y = np.array([1100, 1300, 800, 900, 1000, 1100, 1200])

# Multiply the inverse of XTX with the transpose of X, and then multiply the result by y. Call the result w.
w = XTX_inv.dot(X.T).dot(y)

# What's the sum of all the elements of the result?
w.sum()

np.float64(0.36919696904925203)